CREATE TABLE `activity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(42) NOT NULL,
  `path` TEXT NOT NULL,
  `file` BOOLEAN NOT NULL DEFAULT TRUE,
  `action` ENUM('CREATE','RENAME','DELETE', 'MOVE', 'SHARE') NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
);
