CREATE TABLE `fs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(42) NOT NULL,
  `path` TEXT NOT NULL,
  `ipfs_hash` TEXT NOT NULL,
  `file` BOOLEAN NOT NULL DEFAULT true,
  `file_size` INTEGER(11) NOT NULL DEFAULT 0,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
);
