CREATE TABLE `fs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(42) NOT NULL,
  `path` TEXT NOT NULL,
  `ipfs_hash` TEXT NOT NULL,
  `is_file` BOOLEAN NOT NULL DEFAULT true,
  `file_size` INTEGER(11) NOT NULL DEFAULT 0,
  `file_type` VARCHAR(50),
  `hash` VARCHAR(100) NOT NULL,
  `deleted` BOOLEAN NOT NULL DEFAULT false,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
);
